  # Site settings
title: Your awesome title
email: your-email@domain.com
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" 
url: "http://localhost:4000" 

# permalinks
permalink: pretty

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-sitemap
  - octopress-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
incremental: true
destination: docs/

#Pagination Settings
pagination:
    limit:          false
    per_page:       3

#Social Media & Contect Settings
twitter_username: jekyllrb
github_username:  jekyll
linkedin_username: example
enable_mailto: true
  
# Collection definitions and settings
collections:
  posts:
    permalink: /blog/:categories/:title.html
    output: true
  projects:
    output: true
    permalink: /portfolio/:path/
  tags:
    output: true
    permalink: /:collection/:name/

# File structure settings