# Site settings
title: Your awesome title
email: your-email@domain.com
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" 
url: "http://localhost:4000" 

#Social Media & Contect Settings
twitter_username: jekyllrb
github_username:  jekyll
linkedin_username: example
enable_mailto: true

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  
# Collection definitions and settings
collections:
  projects:
    output: true
    permalink: /projects/:path/
  tags:
    output: true
    permalink: /blog/tag/:name/

# File structure settings