# Site settings
title: Your awesome title
email: your-email@domain.com
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" 
url: "http://localhost:4000" 
repository: 'egeis/jekyll-modern-business'

# Theme Settings
modern:
  blog-index-style: '1'
  portfolio-index-style: '1'
  organization: 'Your Organization'
  defaults: 
    blog:
      frontimagesrc: 'http://placehold.it/900x300' 
      frontimagealt: 'Placeholder Image from placehold.it'
    portfolio:
      frontimagesrc: 'http://placehold.it/700x300'
      frontimagealt: 'Placeholder Image from placehold.it'
# Markdown Settings
markdown: kramdown
kramdown:
   input: GFM
   hard_wrap: false
highlighter: rouge

# Outputting
permalink: /:categories/:title/

# Build Settings
gems:
  - jekyll-feed
  - jekyll-sitemap
  - octopress  
  - octopress-paginate
whitelist:
  - jekyll-feed
  - jekyll-sitemap
  - octopress
  - octopress-paginate
include:
  - .htaccess
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.md
  - CHANGELOG.md
  - .sass-cache
  - .asset-cache
  - .bundle
  - vendor
  - log
encoding: "utf-8"

# Collection Settings
collections:
   posts:
     permalink: /blog/:categories/:title.html
     output: true
   projects:
     output: true
     permalink: /portfolio/:path/