  # Site settings
title: Your awesome title
email: your-email@domain.com
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" 
url: "http://localhost:4000" 

organization: 'Your Organization'

# Theme Settings
blog-index-style: '1'
portfolio-index-style: '1'

# permalinks
permalink: pretty

# Build settings
markdown: kramdown
gems:
  - jekyll-archives
  - jekyll-feed
  - jekyll-sitemap
  - octopress-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
incremental: true

#Pagination Settings
pagination:
    limit:          false
    per_page:       3

#Social Media & Contect Settings
twitter_username: jekyllrb
github_username:  jekyll
linkedin_username: example
enable_mailto: true
  
# Collection definitions and settings
collections:
  posts:
    permalink: /blog/:categories/:title.html
    output: true
  projects:
    output: true
    permalink: /portfolio/:path/
  tags:
    output: true
    permalink: /:collection/:name/

# File structure settings


# Defaults
# defaults:
  # - scope: 
      # path: "/blog/"
      # type: "posts"
  # - values:
      # frontimagesrc: 'http://placehold.it/900x300' 
      # frontimagealt: 'Placeholder Image from placehold.it' 
  # - scope:
      # path: "/portfolio/"
      # type: "projects"
  # - values:
       # frontimagesrc: 'http://placehold.it/700x300'
       # frontimagealt: 'Placeholder Image from placehold.it'