# Site settings
title: Your awesome title
email: your-email@domain.com
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" 
url: "http://localhost:4000" 
repository: 'egeis/jekyll-modern-business'

paging:
  permalink: /page:num/
  blog:
    per_page: 4
    category_dir: 'blog'
  project:
    per_page: 6
    category_dir: 'portfolio'

# Theme Settings
modern:
  blog-index-style: '1'
  portfolio-index-style: '1'
  organization: 'Your Organization'
  defaults: 
    blog:
      frontimagesrc: 'http://placehold.it/900x300' 
    portfolio:
      frontimagesrc: 'http://placehold.it/700x300'

# Markdown Settings
markdown: kramdown
kramdown:
   input: GFM
   hard_wrap: false
highlighter: rouge

# Outputting
permalink: /:categories/:title/

# Build Settings
gems:
  - jekyll-feed
  - jekyll-sitemap
  - octopress  
whitelist:
  - jekyll-feed
  - jekyll-sitemap
  - octopress
include:
  - .htaccess
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.md
  - CHANGELOG.md
  - .sass-cache
  - .asset-cache
  - .bundle
  - vendor
  - log
encoding: "utf-8"

# Collection Settings
collections:
   posts:
     permalink: /blog/:categories/:title.html
     output: true
   projects:
     output: true
     permalink: /portfolio/:categories/:title.html
   members:
     output: false
   customers:
     output: false   

# Octopress settings
post_ext: md
page_ext: html

# Default templates for posts and pages
post_layout: post
page_layout: default

# Format titles with titlecase?
titlecase: true

# Change default template file (in _templates/)
post_template: post
page_template: page
draft_template: draft	 